apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "default.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "default.labels" . | nindent 4 }}
    {{- if .Values.main.deploymentLabels }}
    {{- toYaml .Values.main.deploymentLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.main.deploymentAnnotations }}
  annotations:
    {{- toYaml .Values.main.deploymentAnnotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "default.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/type: master
  template:
    metadata:
      annotations:
        checksum/config: {{ print .Values.main | sha256sum }}
        {{- with .Values.main.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "default.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/type: master
        {{- if .Values.main.podLabels }}
          {{ toYaml .Values.main.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.main.serviceAccount.enabled }}
      serviceAccountName: {{ include "default.serviceAccountName" . }}
      {{- else }}
      automountServiceAccountToken: false
      {{- end }}
      securityContext:
        {{- toYaml .Values.main.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{- if .Values.main.config }}
            - configMapRef:
                name: {{ include "default.fullname" . }}-app-config
            {{- end }}
           {{- if .Values.main.secret }}
            - secretRef:
                name: {{ include "default.fullname" . }}-app-secret
            {{- end }}
          env:
            - name: FLAG
              value: "{{ .Values.main.flag }}"
          ports:
            - name: challenge-port
              containerPort: {{ .Values.main.expose.port }}
              protocol: TCP
          {{- with .Values.main.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.main.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.main.resources | nindent 12 }}
          dnsPolicy: "{{ .Values.main.network.dnsPolicy }}"
          dnsConfig:
            {{- toYaml .Values.main.network.dnsConfig | nindent 12 }}
